package com.journey.control
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.json.JSONObject
private val Navy=Color(0xFF06121E); private val Cyan=Color(0xFF35D9FF)
@Composable fun JourneyApp(vm:JourneyViewModel){val s by vm.state.collectAsState();var tab by remember{mutableIntStateOf(0)};MaterialTheme(colorScheme=darkColorScheme(primary=Cyan,background=Color.Black,surface=Navy)){Scaffold(containerColor=Color.Black,topBar={Header(s)},bottomBar={Nav(tab){tab=it}}){pad->Box(Modifier.padding(pad).fillMaxSize().background(Color.Black)){when(tab){0->Home(vm,s);1->Car(vm,s);2->MapPage(s);3->Obd(vm,s);else->Settings(vm,s)}}}}}
@Composable private fun Header(s:VehicleState)=Row(Modifier.fillMaxWidth().background(Color.Black).padding(16.dp),Arrangement.SpaceBetween,Alignment.CenterVertically){Column{Text("JOURNEY",fontWeight=FontWeight.Black);Text(if(s.online)"ONLINE • "+s.internetRoute else "LOCAL • BLE",color=if(s.online)Color.Green else Cyan,style=MaterialTheme.typography.labelSmall)};Icon(Icons.Default.DirectionsCar,null,tint=Cyan)}
@Composable private fun Nav(sel:Int,set:(Int)->Unit)=NavigationBar(containerColor=Color.Black){listOf("الرئيسية" to Icons.Default.Home,"السيارة" to Icons.Default.DirectionsCar,"الخريطة" to Icons.Default.Map,"OBD" to Icons.Default.Build,"الإعدادات" to Icons.Default.Settings).forEachIndexed{i,x->NavigationBarItem(sel==i,{set(i)},{Icon(x.second,null)},{Text(x.first)})}}
@Composable private fun Page(content:@Composable ColumnScope.()->Unit)=Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(14.dp),content=content)
@Composable private fun CardX(title:String,content:@Composable ColumnScope.()->Unit)=Card(colors=CardDefaults.cardColors(containerColor=Navy),shape=RoundedCornerShape(24.dp)){Column(Modifier.fillMaxWidth().padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(title,color=Cyan,fontWeight=FontWeight.Bold);content()}}
@Composable private fun Home(vm:JourneyViewModel,s:VehicleState)=Page{CardX("DODGE JOURNEY SE 2017"){Box(Modifier.fillMaxWidth().height(180.dp),contentAlignment=Alignment.Center){Icon(Icons.Default.DirectionsCar,null,Modifier.size(150.dp),tint=Color.White)};Text(if(s.doorsOpen)"الباب مفتوح" else "الأبواب مغلقة");Text("27A77884",color=Color.LightGray)};Controls(vm,s);Telemetry(s);CardX("Keyless"){Text("BLE مخصص للقرب والفتح/القفل التلقائي");Text("Owner: "+(if(s.ownerKnown)"مسجل" else "بانتظار المزامنة")+" • "+s.ownerCount+" جهاز")}}
@Composable private fun Controls(vm:JourneyViewModel,s:VehicleState)=CardX("التحكم"){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Action("فتح",Icons.Default.LockOpen,Modifier.weight(1f)){vm.send("unlock")};Action("قفل",Icons.Default.Lock,Modifier.weight(1f)){vm.send("lock")}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){Action("تشغيل",Icons.Default.PowerSettingsNew,Modifier.weight(1f)){vm.send("remote_start")};Action("إنذار",Icons.Default.Notifications,Modifier.weight(1f)){vm.send("horn")}};Text("المحرك: "+(if(s.engineRunning)"شغال" else "مطفي")+" • الريموت: "+(if(s.remotePowered)"ON" else "OFF"))}
@Composable private fun Action(t:String,i:androidx.compose.ui.graphics.vector.ImageVector,m:Modifier=Modifier,on:()->Unit)=Button(on,m.height(58.dp)){Icon(i,null);Spacer(Modifier.width(6.dp));Text(t)}
@Composable private fun Telemetry(s:VehicleState)=CardX("بيانات السيارة"){Text("RPM "+s.rpm+"   •   "+s.speed+" km/h");Text("حرارة "+s.coolant+"°C   •   بطارية "+String.format("%.2f",s.battery)+" V");Text("وقود "+s.fuel+"%   •   OBD "+(if(s.obdConnected)"متصل" else s.obdStatus))}
@Composable private fun Car(vm:JourneyViewModel,s:VehicleState)=Page{Controls(vm,s);Telemetry(s);CardX("الحالة"){Text("القفل: "+(if(s.locked)"مقفلة" else "مفتوحة"));Text("آخر حدث: "+s.lastEvent)}}
@Composable private fun MapPage(s:VehicleState)=Page{CardX("الخريطة والتتبع"){Text(if(s.gpsValid) s.latitude.toString()+", "+s.longitude else "بانتظار GPS من ESP / الشريحة");Icon(Icons.Default.LocationOn,null,Modifier.size(100.dp),tint=Cyan)}}
@Composable private fun Obd(vm:JourneyViewModel,s:VehicleState)=Page{CardX("OBD"){Text("الحالة: "+s.obdStatus);Telemetry(s);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.send("obd_search",JSONObject().put("obdAdapter",JSONObject().put("transport","BLE")))}){Text("بحث BLE")};Button({vm.send("obd_search",JSONObject().put("obdAdapter",JSONObject().put("transport","WIFI")))}){Text("بحث Wi-Fi")}}};CardX("الأعطال"){Button({vm.send("obd_scan_dtc")}){Text("قراءة DTC")};Button({vm.send("obd_clear_dtc",JSONObject().put("obdClearConfirmed",true))},colors=ButtonDefaults.buttonColors(containerColor=Color(0xFF8B1E1E))){Text("مسح DTC")}}}
@Composable private fun Settings(vm:JourneyViewModel,s:VehicleState)=Page{CardX("أولوية الاتصال"){Text(s.connectionPriority);Text("الـKeyless يبقى BLE دائماً")};CardX("Wi-Fi في ESP"){Text((if(s.wifiEnabled)"مفعّل" else "مطفي")+" • "+s.wifiSsid+" • "+s.wifiStatus);Row{Button({vm.send("wifi_search")}){Text("بحث الشبكات")};Spacer(Modifier.width(8.dp));Button({vm.send("wifi_config",JSONObject().put("wifiSettings",JSONObject().put("enabled",!s.wifiEnabled)))}){Text(if(s.wifiEnabled)"إطفاء" else "تشغيل")}}};CardX("الشريحة و4G"){Text((if(s.cellularEnabled)"مفعلة" else "مطفيّة")+" • "+s.cellularNetwork+" • "+s.cellularStatus);Text("نقطة الاتصال: "+(if(s.hotspotRunning)"شغالة" else "متوقفة"))};CardX("النظام والتحديث"){Text("Firmware ESP32: v12.65");Text("JOURNEY Android: 2.4.13 (44)");Text("Owner / Keyless / OBD / Wi-Fi / Cellular")};CardX("حول"){Text("JOURNEY");Text("Dodge Journey Connected Control");Text("تصميم: مهند الربيعي")}}
