name: JourneyControl
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "18.0"
packages:
  CocoaMQTT:
    url: https://github.com/emqx/CocoaMQTT.git
    from: 2.1.0
targets:
  JourneyControl:
    type: application
    platform: iOS
    sources:
      - JourneyControl
      - Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abuseif.journey
        CODE_SIGN_ENTITLEMENTS: JourneyControl/JourneyControl.entitlements
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) JOURNEY_APP"
        INFOPLIST_FILE: JourneyControl/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: 6778LWD4ZB
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: 2.4.38
        CURRENT_PROJECT_VERSION: 70
    dependencies:
      - package: CocoaMQTT
      - target: JourneyWidgetExtension
  JourneyWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - JourneyWidget
      - Shared
      - path: JourneyControl/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abuseif.journey.widget
        CODE_SIGN_ENTITLEMENTS: JourneyWidget/JourneyWidget.entitlements
        APPLICATION_EXTENSION_API_ONLY: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        PRODUCT_NAME: JourneyWidget
        INFOPLIST_FILE: JourneyWidget/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: YES
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: 6778LWD4ZB
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: 2.4.38
        CURRENT_PROJECT_VERSION: 70
