import Foundation

/// The app language is independent of the iPhone system language.
/// Resolve at presentation time so every view and newly generated message uses
/// the same preference as the language picker.
func JL(_ arabic: String, _ english: String) -> String {
    UserDefaults.standard.string(forKey: "journey.settings.language") == "en"
        ? english : arabic
}

/// Translate previously generated status and history messages when language changes.
func JLStored(_ text: String) -> String {
    let english = UserDefaults.standard.string(forKey: "journey.settings.language") == "en"
    if let exact = english ? journeyStoredTranslations[text] : journeyStoredArabic[text] { return exact }
    let range = NSRange(text.startIndex..., in: text)
    for pair in journeyStoredPatterns {
        let regex = english ? pair.0 : pair.2
        if regex.firstMatch(in: text, range: range) != nil {
            return regex.stringByReplacingMatches(in: text, range: range, withTemplate: english ? pair.1 : pair.3)
        }
    }
    return text
}

private let journeyStoredTranslations: [String: String] = [
    "سيارة جورني": "Journey vehicle",
    "أدخل الاسم ومعرّف الجهاز": "Enter a name and device ID",
    "المعرّف يقبل حروف إنكليزية وأرقام و - أو _ فقط": "Use English letters, numbers, - or _ for the ID",
    "هذا المعرّف مضاف مسبقاً": "This device ID is already added",
    "اكتب اسماً للبطاقة": "Enter a card name",
    "إضافة مفتاح NFC تجريبي": "Add a test NFC key",
    "حذف مفتاح NFC": "Delete NFC key",
    "تم تأكيد مفتاح iPhone": "iPhone key confirmed",
    "رُفض مفتاح iPhone": "iPhone key rejected",
    "اختبار داخل التطبيق": "In-app test",
    "قفل السيارة": "Lock vehicle",
    "فتح السيارة": "Unlock vehicle",
    "تشغيل السيارة": "Start vehicle",
    "غير مهيأ": "Not configured",
    "غير متصل": "Disconnected",
    "جاري الاتصال": "Connecting",
    "متصل": "Connected",
    "هذا الآيفون غير مسجّل كمالك على ESP. سجّله من أجهزة المالك.": "This iPhone is not registered as an ESP owner. Register it in Owner devices.",
    "وصل طلب طاقة الريموت لمسار الاتصال، لكن ESP لم يؤكد تغيير الحالة. راجع الاتصال وإصدار ESP.": "The remote power request was sent, but ESP did not confirm the state change. Check the connection and ESP firmware.",
    "أدخل إعدادات MQTT أولاً": "Enter MQTT settings first",
    "ترتيب الاتصال غير صحيح": "Invalid connection order",
    "لا يوجد مسار اتصال متاح حسب الأولوية المحددة": "No connection route is available in the selected order",
    "تعذر إرسال إعدادات الدخول الذكي": "Could not send smart entry settings",
    "تعذر الاتصال بـ ESP حسب الأولوية المحددة": "Could not connect to ESP using the selected order",
    "OBD غير متصل": "OBD disconnected",
    "لا توجد بيانات محرك كافية حتى يكتمل التحليل.": "Not enough engine data to complete the analysis.",
    "شغّل السويج وتأكد أن قطعة OBD BLE ظاهرة وغير متصلة بتطبيق آخر.": "Turn the ignition on and make sure the BLE OBD adapter is visible and not connected to another app.",
    "حرارة سائل التبريد مرتفعة جداً": "Coolant temperature is very high",
    "أوقف الاختبار بأمان وافحص منظومة التبريد وحساس الحرارة يدوياً.": "Stop the test safely and manually inspect the cooling system and temperature sensor.",
    "حرارة المحرك أعلى من المعتاد": "Engine temperature is above normal",
    "راقب تغيّر الحرارة وافحص المراوح ومستوى السائل ضمن إجراءات الورشة.": "Monitor temperature changes and inspect fans and coolant level using workshop procedures.",
    "فولتية البطارية منخفضة جداً": "Battery voltage is very low",
    "القراءة %.1fV وقد تكون البطارية مفرغة أو القياس غير صحيح.": "The reading is %.1fV. The battery may be discharged or the measurement may be incorrect.",
    "أكد القراءة بملتيميتر وافحص البطارية والتوصيلات.": "Verify with a multimeter and inspect the battery and connections.",
    "فولتية البطارية منخفضة": "Battery voltage is low",
    "القراءة %.1fV والمحرك متوقف.": "The reading is %.1fV with the engine stopped.",
    "نفّذ اختبار بطارية وشحن قبل الاعتماد على الاستنتاج.": "Test the battery and charging system before drawing conclusions.",
    "فولتية الشحن تحتاج تحقق": "Charging voltage needs verification",
    "القراءة %.1fV مع حالة تشغيل ظاهرة.": "The reading is %.1fV while the engine appears to be running.",
    "أكد حالة المحرك وقس خرج الشحن بأداة مستقلة.": "Verify engine status and measure charging output independently.",
    "أكواد أعطال مسجلة": "Stored diagnostic trouble codes",
    "افتح تقرير الأكواد وافحص السبب؛ المساعد لا يمسح الأكواد ولا يرسل أوامر للسيارة.": "Open the code report and inspect the cause. The assistant does not clear codes or send vehicle commands.",
    "لا يوجد تثبيت GPS": "No GPS fix",
    "التعقب لا يملك موقعاً صالحاً حالياً.": "Tracking does not currently have a valid position.",
    "اختبر الهوائي بمكان مفتوح وراجع زمن آخر تحديث.": "Test the antenna outdoors and check the last update time.",
    "لا توجد ملاحظة واضحة": "No clear issue detected",
    "القراءات المتاحة لا تُظهر حالة تتجاوز حدود التنبيه المحافظة.": "Available readings do not exceed the conservative alert thresholds.",
    "استمر بجمع البيانات وقارنها بالفحص اليدوي؛ هذا ليس تشخيصاً نهائياً.": "Continue collecting data and compare it with manual inspection. This is not a final diagnosis.",
    "تم تشغيل السيارة": "Engine started",
    "تم إطفاء السيارة": "Engine stopped",
    "تحذير: حرارة المحرك مرتفعة": "Warning: high engine temperature",
    "تحذير: فولت بطارية السيارة منخفض": "Warning: low vehicle battery voltage",
    "اقتربت من السيارة — تم اكتشاف الهاتف": "Approaching vehicle — phone detected",
    "ابتعدت عن السيارة — خرج الهاتف من نطاق القرب": "Leaving vehicle — phone outside proximity range",
    "اقتربت من السيارة — تم فتح السيارة": "Approaching vehicle — vehicle unlocked",
    "ابتعدت عن السيارة — تم قفل السيارة": "Leaving vehicle — vehicle locked",
    "يوجد تحديث جديد من السيارة": "New vehicle update",
    "تم قفل السيارة": "Vehicle locked",
    "تم فتح السيارة": "Vehicle unlocked",
    "انقطع BLE — تم تأكيد قفل السيارة مرة ثانية": "BLE disconnected — vehicle lock confirmed again",
    "الباب مفتوح": "Door open",
    "الأبواب مغلقة": "Doors closed",
    "الريموت اشتغل": "Remote power on",
    "الريموت انطفأ بعد تنفيذ المهمة": "Remote power off after the action",
    "اللايت اشتغل": "Lights on",
    "اللايت انطفأ": "Lights off",
    "الإنذار يعمل": "Alarm active",
    "OBD متصل": "OBD connected",
    "OBD انقطع": "OBD disconnected",
    "السيارة متاحة": "Vehicle online",
    "اتصال السيارة انقطع": "Vehicle disconnected",
    "ظهر كود فحص جديد": "New diagnostic code detected",
    "تحذير: بطارية السيارة منخفضة": "Warning: low vehicle battery",
    "الإشارتان تعملان": "Both turn signals active",
    "إشارة اليسار تعمل": "Left turn signal active",
    "إشارة اليمين تعمل": "Right turn signal active",
    "الإشارات انطفأت": "Turn signals off",
    "غير متاح": "Unavailable",
    "قريب": "Near",
    "متوسط": "Medium",
    "بعيد": "Far",
    "فعّل البلوتوث": "Enable Bluetooth",
    "جاري اتصال BLE": "Connecting BLE",
    "جاهز للبلوتوث": "Bluetooth ready",
    "BLE متصل": "BLE connected",
    "فشل اتصال BLE": "BLE connection failed",
    "انقطع BLE — إعادة اتصال": "BLE disconnected — reconnecting",
    "تعذر تجهيز أمر BLE": "Could not prepare BLE command",
    "خاصية أوامر BLE غير متاحة": "BLE command characteristic unavailable",
    "تم تأكيد أمر BLE": "BLE command confirmed",
    "BLE متصل — مزامنة": "BLE connected — synchronizing",
    "جاري البحث عن ESP": "Searching for ESP",
    "تم فتح الدخول الذكي": "Smart entry unlocked",
    "تم تسجيل ابتعاد الدخول الذكي": "Smart entry departure recorded",
    "فعّل Face ID من إعدادات iPhone أولاً.": "Enable Face ID in iPhone settings first.",
    "لم يتم تأكيد Face ID، لذلك لم يُرسل أي أمر إلى السيارة.": "Face ID was not confirmed. No vehicle command was sent.",
    "إضافة من البلوتوث": "Add via Bluetooth",
    "جاري البحث عن البوردات…": "Searching for boards…",
    "اضغط بحث للعثور على البوردات": "Tap Search to find boards",
    "مضاف": "Added",
    "بحث بالبلوتوث": "Search Bluetooth",
    "الأجهزة المحفوظة": "Saved devices",
    "الأجهزة": "Devices",
    "تم": "Done",
    "معلومات الجهاز": "Device details",
    "مثال: جورني أبو سيف": "Example: Abu Saif's Journey",
    "مثال: journey-02": "Example: journey-02",
    "معرّف الجهاز لازم يطابق DEVICE_ID المكتوب داخل config.h لذلك البورد.": "The device ID must match DEVICE_ID in that board's config.h.",
    "إضافة جهاز": "Add device",
    "إلغاء": "Cancel",
    "إضافة": "Add",
    "مفاتيح NFC": "NFC keys",
    "مفتاح iPhone": "iPhone key",
    "NFC Tag يفتح التطبيق، ثم Face ID وBLE": "NFC tag opens the app, then Face ID and BLE",
    "أساسي": "Primary",
    "Face ID إلزامي قبل تنفيذ أي طلب": "Face ID is required before every request",
    "اختبار تمرير الآيفون": "Test iPhone tap",
    "الآيفون": "iPhone",
    "التاغ لا يحمل أمراً أو مفتاحاً سرياً. للاختبار أنشئ Automation في Shortcuts يفتح journeycontrol://nfc عند تمرير الآيفون.": "The tag contains no command or secret key. For testing, create a Shortcuts automation that opens journeycontrol://nfc when you tap the iPhone.",
    "ماكو بطاقات مضافة": "No cards added",
    "حالياً الإضافة تجريبية. التسجيل الحقيقي يتفعل بعد ربط PN532 بالـESP.": "Adding cards is currently a test. Real enrollment requires PN532 connected to ESP.",
    "إضافة بطاقة فحص": "Add test card",
    "فحص": "Test",
    "حذف": "Delete",
    "البطاقات والمفاتيح": "Cards and keys",
    "الحماية": "Security",
    "إجباري": "Required",
    "Face ID للآيفون": "iPhone Face ID",
    "منع القراءة المكررة": "Prevent repeated reads",
    "لا يوجد أمر إطفاء ضمن مسار NFC": "NFC does not send an engine stop command",
    "آخر النشاطات": "Recent activity",
    "ماكو نشاط مسجل بعد": "No activity yet",
    "المفتاح": "Key",
    "مثال: بطاقة أبو سيف": "Example: Abu Saif's card",
    "النوع": "Type",
    "هذه إضافة فحص محلية فقط، وما ترسل أمراً إلى السيارة.": "This is a local test only. It sends no vehicle command.",
    "عند وصول PN532 نستبدل المعرّف التجريبي بالمعرّف الذي يرجعه ESP بعد التحقق من البطاقة.": "When PN532 is connected, the test ID will be replaced by the ID returned by ESP after card verification.",
    "إضافة مفتاح NFC": "Add NFC key",
    "معلومات المفتاح": "Key details",
    "الاسم": "Name",
    "المعرّف": "ID",
    "الصلاحيات": "Permissions",
    "المفتاح مفعّل": "Key enabled",
    "يسمح بالتشغيل عن بُعد": "Allow remote start",
    "إلغاء الإطفاء والقفل بالتمرير الثاني حسب الاتفاق الحالي.": "Second-tap shutdown and locking are disabled in the current configuration.",
    "تعديل المفتاح": "Edit key",
    "حفظ": "Save",
    "دودج جورني بلاك توب بيضاء من الأمام": "White Dodge Journey Blacktop, front view",
    "مقفلة": "Locked",
    "مفتوحة": "Unlocked",
    "فحص البورد المحلي": "Local board diagnostics",
    "إغلاق": "Close",
    "قراءة OBD عبر BLE": "OBD over BLE",
    "شاشة HUD": "HUD display",
    "تأكيد التشغيل عن بُعد": "Confirm remote start",
    "إرسال الأمر": "Send command",
    "تأكيد التشغيل عن بُعد لسيارة JOURNEY": "Confirm JOURNEY remote start",
    "سيرسل التطبيق أمر تشغيل حقيقي إلى ESP. تأكد أن السيارة بمكان آمن والقير على P.": "The app will send a real start command to ESP. Make sure the vehicle is in a safe location and the transmission is in P.",
    "تعذر التأكيد": "Confirmation failed",
    "حسنًا": "OK",
    "معلومات": "About",
    "السيارة": "Vehicle",
    "الخريطة": "Map",
    "الرئيسية": "Home",
    "أضف جهاز السيارة أولاً حتى يعمل الاختصار.": "Add a vehicle device first to use this shortcut.",
    "تأكيد تشغيل طاقة ريموت السيارة": "Confirm vehicle remote power on",
    "تأكيد إطفاء طاقة ريموت السيارة": "Confirm vehicle remote power off",
    "إعدادات اتصال ESP": "ESP connection settings",
    "تعمل": "Running",
    "متوقفة": "Stopped",
    "GPS متصل": "GPS connected",
    "GPS غير متاح": "GPS unavailable",
    "الدخول الذكي": "Smart entry",
    "فتح عند الاقتراب وقفل عند الابتعاد — BLE": "Unlock nearby and lock on departure — BLE",
    "الآن": "Now",
    "بانتظار قراءة": "Waiting for a reading",
    "سلامة ومتابعة": "Safety and monitoring",
    "الإنذار جاهز": "Alarm ready",
    "البطارية": "Battery",
    "آخر تحديث": "Last update",
    "لا توجد أوامر بعد": "No commands yet",
    "أجهزة المالك": "Owner devices",
    "جاري التحقق من المدير المحفوظ في ESP…": "Checking the administrator saved on ESP…",
    "لا يوجد مالك مسجّل. سجّل هذا الآيفون كمدير.": "No registered owner. Register this iPhone as administrator.",
    "تسجيل هذا الآيفون كمدير": "Register this iPhone as administrator",
    "هذا الآيفون هو المدير. الأجهزة الجديدة تحتاج موافقتك.": "This iPhone is the administrator. New devices require your approval.",
    "موافقة": "Approve",
    "رفض": "Reject",
    "مسح كل الأجهزة الأخرى": "Remove all other devices",
    "الآيفون الإداري يوافق على ربط هذا الجهاز قبل تفعيل الأوامر.": "The administrator iPhone must approve this device before commands are enabled.",
    "إرسال طلب ربط": "Request pairing",
    "تأكيد إدارة أجهزة مالك JOURNEY": "Confirm JOURNEY owner device management",
    "قفل": "Lock",
    "فتح": "Unlock",
    "تشغيل": "Start",
    "إنذار": "Alarm",
    "إطفاء طاقة الريموت": "Turn remote power off",
    "تشغيل طاقة الريموت": "Turn remote power on",
    "بانتظار تأكيد ESP…": "Waiting for ESP confirmation…",
    "ESP غير متصل": "ESP disconnected",
    "مشتغل الآن • اضغط للإطفاء": "On now • Tap to turn off",
    "طافي • Face ID": "Off • Face ID",
    "مشتغل": "On",
    "طافي": "Off",
    "OBD مباشر • المحرك شغال": "Live OBD • Engine running",
    "OBD مباشر • IGN/ACC": "Live OBD • IGN/ACC",
    "KONNWEI متصلة • CAN نايم": "KONNWEI connected • CAN asleep",
    "بانتظار OBD": "Waiting for OBD",
    "بيانات السيارة": "Vehicle data",
    "السرعة": "Speed",
    "الحرارة": "Temperature",
    "فولت البطارية": "Battery voltage",
    "بنزين": "Fuel",
    "OBD رد/ث": "OBD responses/s",
    "بانتظار GPS": "Waiting for GPS",
    "السرعة وRPM والحرارة والبنزين من OBD؛ حالة الباب واللايت والإشارات تحتاج فحص BCM مخصص": "Speed, RPM, temperature and fuel come from OBD. Door, light and turn signal states require a dedicated BCM test.",
    "المساعد الذكي": "Smart assistant",
    "تحليل وشرح فقط — لا يتحكم بالمخارج ولا يمسح الأعطال": "Analysis and explanation only — no output control or code clearing",
    "أضف أول جهاز": "Add your first device",
    "ابحث عن البورد القريب بالبلوتوث حتى يظهر هنا.": "Search for the nearby board over Bluetooth to show it here.",
    "فتح البحث": "Open search",
    "نظام التحكم والتشخيص الذكي للسيارة": "Smart vehicle control and diagnostics",
    "تصميم وتطوير": "Design and development",
    "مهند الربيعي": "Mohaned Al-Rubaie",
    "الريموت، NFC، OBD، التعقّب والتحليل الذكي ضمن نظام واحد.": "Remote, NFC, OBD, tracking and intelligent analysis in one system.",
    "البريد الإلكتروني": "Email",
    "اتصال": "Connect",
    "تلقائي": "Automatic",
    "سرعة": "Speed",
    "حرارة": "Temperature",
    "كير": "Gear",
    "السرعة mph": "Speed mph",
    "السرعة km/h": "Speed km/h",
    "حرارة ماء المحرك °F": "Engine coolant °F",
    "حرارة ماء المحرك °C": "Engine coolant °C",
    "دورات المحرك RPM": "Engine RPM",
    "نمرة الكير": "Gear position",
    "مطفيّة": "Off",
    "تشغيل شاشة الـHUD": "Enable HUD display",
    "السطوع": "Brightness",
    "المعلومة المعروضة": "Displayed information",
    "نوع العرض": "Display mode",
    "ترتيب الوضع التلقائي": "Automatic mode order",
    "السيارة واقفة": "Vehicle stationary",
    "السيارة تتحرك": "Vehicle moving",
    "الحرارة عالية": "High temperature",
    "حرارة فوراً": "Show temperature immediately",
    "RPM عالي": "High RPM",
    "RPM فوراً": "Show RPM immediately",
    "استخدم بيانات السيارة": "Use vehicle data",
    "يعرض قراءات OBD عبر Bluetooth الحالية.": "Shows current OBD readings over Bluetooth.",
    "قطعة OBD غير متصلة حالياً.": "OBD adapter is currently disconnected.",
    "الصفحة جاهزة للمحاكاة. عند ربط كود ESP تُرسل له: وضع العرض، السطوع، الحدود، والقراءة الحالية عبر BLE.": "This page supports simulation. When ESP firmware is connected, display mode, brightness, thresholds and current readings are sent over BLE.",
    "الاتصال المباشر": "Direct connection",
    "حالة ESP": "ESP status",
    "بانتظار الاتصال": "Waiting for connection",
    "وقت التشغيل": "Uptime",
    "طاقة الريموت": "Remote power",
    "مشتغلة": "On",
    "مطفأة": "Off",
    "بانتظار ESP": "Waiting for ESP",
    "OBD عبر BLE": "OBD over BLE",
    "قطعة OBD": "OBD adapter",
    "متصلة": "Connected",
    "الردود/ث": "Responses/s",
    "آخر حدث": "Last event",
    "إعدادات محفوظة على ESP": "Settings saved on ESP",
    "نبضة زر الريموت": "Remote button pulse",
    "انتظار تشغيل الريموت": "Remote wake delay",
    "فصل طاقة الريموت": "Remote power off delay",
    "سطوع شاشة HUD": "HUD brightness",
    "حفظ الإعدادات على ESP": "Save settings to ESP",
    "الحماية والطاقة": "Security and power",
    "وضع الصيانة": "Maintenance mode",
    "توفير الطاقة": "Power saving",
    "يدوي": "Manual",
    "بدء التوفير بعد": "Start saving after",
    "دقيقة": "minutes",
    "حفظ وضع الطاقة": "Save power mode",
    "إضافة بطاقة NFC الآن": "Add NFC card now",
    "حذف بطاقة NFC": "Delete NFC card",
    "تحديث Firmware": "Firmware update",
    "للتحديث المحلي: اتصل من الآيفون بشبكة JOURNEY-ESP الظاهرة في Serial Monitor، ثم اختر ملف firmware.bin.": "For a local update, connect the iPhone to the JOURNEY-ESP network shown in Serial Monitor, then select firmware.bin.",
    "جاري رفع التحديث…": "Uploading update…",
    "اختيار ملف firmware.bin": "Select firmware.bin",
    "رابط HTTPS لملف firmware.bin": "HTTPS URL for firmware.bin",
    "تحديث عبر 4G من الرابط": "Update via 4G from URL",
    "رابط التحديث يجب أن ينتهي بملف firmware.bin متاح للتحميل المباشر. ESP ينزله عبر شريحته ثم يعيد التشغيل.": "The update URL must provide a directly downloadable firmware.bin. ESP downloads it through its cellular connection, then restarts.",
    "الإعدادات تحفظ داخل ESP، لذلك تبقى بعد فصل الكهرباء ولا تحتاج كمبيوتر.": "Settings are stored on ESP and remain after power loss. No computer is required.",
    "تم إرسال الإعدادات إلى ESP": "Settings sent to ESP",
    "تعذر إرسال الإعدادات": "Could not send settings",
    "جاري رفع الملف…": "Uploading file…",
    "تم التحديث؛ ESP يعيد التشغيل الآن": "Update complete; ESP is restarting",
    "تم إرسال رابط التحديث؛ ESP يبدأ التنزيل عبر 4G": "Update URL sent; ESP is downloading over 4G",
    "تعذر إرسال رابط التحديث": "Could not send update URL",
    "تم حفظ وضع توفير الطاقة": "Power saving mode saved",
    "تعذر حفظ وضع الطاقة": "Could not save power mode",
    "تم إرسال الأمر إلى ESP": "Command sent to ESP",
    "تعذر إرسال الأمر": "Could not send command",
    "بانتظار قطعة OBD": "Waiting for OBD adapter",
    "ESP يرسل طلبات OBD القياسية للقراءة فقط عبر BLE أو Wi‑Fi؛ أوامر التحكم غير مستخدمة، ومسح الأخطاء لا يتم إلا بتأكيدك.": "ESP sends standard read-only OBD requests over BLE or Wi-Fi. Control commands are not used. Clearing codes requires your confirmation.",
    "الحالة": "Status",
    "الردود بالثانية": "Responses per second",
    "فحص PIDs": "PID scan",
    "PID الحالي": "Current PID",
    "مجموع الردود": "Total responses",
    "حالة السويتش / ACC": "Ignition / ACC status",
    "حالة CAN": "CAN status",
    "صاحي": "Awake",
    "نايم / بانتظار الاستيقاظ": "Asleep / Waiting to wake",
    "آخر رد": "Last response",
    "اتصال OBD": "OBD connection",
    "نوع الاتصال": "Connection type",
    "القطعة الأساسية KONNWEI محفوظة داخل ESP. البحث العام يعمل فقط عند ضغط الزر لتغيير القطعة.": "The primary KONNWEI adapter is saved on ESP. General scanning starts only when you tap the button to change adapters.",
    "ESP يبحث عن شبكات Wi‑Fi القريبة؛ اختر شبكة قطعة OBD ثم أدخل الباسورد إذا موجود.": "ESP searches nearby Wi-Fi networks. Select the OBD adapter network, then enter its password if needed.",
    "بحث ESP عن قطع BLE": "ESP search for BLE adapters",
    "بحث ESP عن شبكات Wi‑Fi": "ESP search for Wi-Fi networks",
    "اسم القطعة كما يظهر بالبلوتوث، مثال V-LINK": "Bluetooth adapter name, e.g. V-LINK",
    "اسم شبكة Wi‑Fi لقطعة OBD": "OBD adapter Wi-Fi network name",
    "باسورد الشبكة (إن وجد)": "Network password (if any)",
    "عنوان قطعة OBD": "OBD adapter address",
    "المنفذ": "Port",
    "اختيار وحفظ واتصال": "Select, save and connect",
    "المحفوظة": "Saved",
    "الرجوع إلى KONNWEI الأساسية": "Return to primary KONNWEI",
    "الأخطاء والتحليل": "Faults and analysis",
    "الأكواد": "Codes",
    "لا توجد أكواد": "No codes",
    "فحص الأكواد يدوي فقط؛ لا يوجد فحص دوري بالخلفية.": "Code scanning is manual only. There is no periodic background scan.",
    "فحص الأخطاء الآن": "Scan trouble codes now",
    "أفهم أن المسح قد يطفي اللمبة مؤقتاً": "I understand clearing may temporarily turn off the warning lamp",
    "جاري مسح الأخطاء…": "Clearing trouble codes…",
    "مسح أخطاء السيارة": "Clear vehicle trouble codes",
    "أطفئ المحرك أولاً؛ المسح مقفول أثناء التشغيل.": "Stop the engine first. Clearing is blocked while running.",
    "OBD القياسي يعطي سرعة وRPM وحرارة؛ الأبواب واللايتات والإشارات ليست ضمن PIDs القياسية.": "Standard OBD provides speed, RPM and temperature. Doors, lights and turn signals are not standard PIDs.",
    "تم حفظ الاسم؛ ESP يبحث ويتصل به تلقائياً.": "Name saved; ESP will search and connect automatically.",
    "تعذر إرسال الاختيار إلى ESP": "Could not send selection to ESP",
    "أُرسل بحث BLE إلى ESP؛ انتظر 20 ثانية، وتظهر حتى الأجهزة بدون اسم.": "BLE search sent to ESP. Wait 20 seconds. Unnamed devices are also shown.",
    "أُرسل بحث Wi‑Fi إلى ESP؛ البحث يبدأ فوراً وتظهر الشبكات المخفية أيضاً.": "Wi-Fi search sent to ESP. Search starts immediately and includes hidden networks.",
    "تعذر إرسال طلب البحث إلى ESP": "Could not send search request to ESP",
    "تم الرجوع إلى KONNWEI الأساسية.": "Returned to primary KONNWEI.",
    "تعذر الرجوع للقطعة الأساسية": "Could not return to primary adapter",
    "بدأ فحص أخطاء OBD.": "OBD trouble code scan started.",
    "تعذر إرسال طلب فحص الأخطاء": "Could not send code scan request",
    "تأكيد مسح أخطاء OBD لسيارة JOURNEY": "Confirm clearing JOURNEY OBD trouble codes",
    "لم يتم تأكيد Face ID": "Face ID was not confirmed",
    "أُرسل طلب المسح؛ سيتم فحص الأكواد من جديد.": "Clear request sent. Codes will be scanned again.",
    "تعذر إرسال أمر المسح": "Could not send clear command",
    "المحرك شغال": "Engine running",
    "IGN/ACC صاحي — المحرك طافي": "IGN/ACC awake — Engine off",
    "طافي / CAN نايم": "Off / CAN asleep",
    "غير معروف": "Unknown",
    "بانتظار القطعة الأساسية": "Waiting for primary adapter",
    "جاري الاتصال بـ KONNWEI": "Connecting to KONNWEI",
    "تهيئة ELM327": "Initializing ELM327",
    "الاتصال بكمبيوتر السيارة": "Connecting to vehicle ECU",
    "قراءة رقم الشاصي VIN": "Reading VIN",
    "فحص PIDs المدعومة": "Scanning supported PIDs",
    "قراءة بيانات السيارة": "Reading vehicle data",
    "فحص الأخطاء المخزنة": "Scanning stored codes",
    "فحص الأخطاء المعلقة": "Scanning pending codes",
    "فحص الأخطاء الدائمة": "Scanning permanent codes",
    "اكتمل فحص الأخطاء": "Code scan complete",
    "بحث يدوي عن قطع BLE": "Manual BLE adapter search",
    "اكتمل البحث اليدوي": "Manual search complete",
    "لم يتم العثور على القطعة": "Adapter not found",
    "بانتظار رد OBD": "Waiting for OBD response",
    "KONNWEI متصلة — بانتظار CAN": "KONNWEI connected — Waiting for CAN",
    "فحص استيقاظ CAN": "Checking CAN wake-up",
    "CAN اشتغل — قراءة VIN": "CAN awake — Reading VIN",
    "متصل — قراءة مباشرة": "Connected — Live readings",
    "بدء فحص الأخطاء": "Starting code scan",
    "انقطع رد القطعة — إعادة اتصال": "Adapter stopped responding — Reconnecting",
    "رد ECU غير صالح": "Invalid ECU response",
    "VIN غير صالح — توقف الفحص": "Invalid VIN — Scan stopped",
    "KONNWEI هي القطعة الأساسية": "KONNWEI is the primary adapter",
    "فعّل Bluetooth ثم أعد البحث": "Enable Bluetooth and search again",
    "جاري مسح كل أجهزة BLE القريبة…": "Scanning all nearby BLE devices…",
    "لم يظهر أي جهاز BLE؛ تأكد من تفعيل Bluetooth ومن أن الجهاز القريب يعلن عن نفسه.": "No BLE devices found. Enable Bluetooth and make sure the nearby device is advertising.",
    "ظهرت أجهزة BLE القريبة. اختر قطعة OBD ثم اضغط اختيار وحفظ واتصال.": "Nearby BLE devices found. Select an OBD adapter, then tap Select, save and connect.",
    "الموقع الحي": "Live location",
    "GPS بانتظار": "Waiting for GPS",
    "حالة السيارة": "Vehicle status",
    "فتح في خرائط Apple": "Open in Apple Maps",
    "تظهر السيارة هنا تلقائياً عندما ينشر ESP إحداثيات GPS.": "The vehicle appears here automatically when ESP publishes GPS coordinates.",
    "الخريطة والتعقّب": "Map and tracking",
    "موقع السيارة الحالي": "Current vehicle location",
    "، ": ", ",
    "بانتظار موقع السيارة من GPS": "Waiting for vehicle GPS location",
    "تفعيل الدخول الذكي": "Enable smart entry",
    "عند الاتصال الآمن بالـESP: يفتح عند الاقتراب ويقفل بعد الابتعاد.": "With a secure ESP connection, unlock on approach and lock after departure.",
    "مفتاح الآيفون": "iPhone key",
    "مسافات تقريبية": "Approximate distances",
    "مسافة الفتح": "Unlock distance",
    "مسافة القفل": "Lock distance",
    "ثبات الإشارة": "Signal stability",
    "تثبيت القرب قبل الفتح": "Confirm proximity before unlock",
    " ث": " s",
    "تأخير القفل بعد الابتعاد": "Lock delay after departure",
    "ريموت السيارة الاحتياطي": "Spare vehicle remote",
    "يبقى الريموت مفعّل أثناء وجود الآيفون": "Keep remote powered while iPhone is nearby",
    "عند الاقتراب: ESP يشغّل 3.3V للريموت، ينتظر ثانية، ثم ينفذ الفتح. عند الابتعاد: يقفل أولاً، ينتظر ثانيتين، ثم يفصل تغذية الريموت.": "On approach, ESP supplies 3.3V to the remote, waits one second, then unlocks. On departure, it locks first, waits two seconds, then cuts remote power.",
    "يبقى مفتاح السيارة موجوداً أثناء وقوفك داخلها، فلا ينفصل الريموت مباشرة بعد الفتح.": "The vehicle key remains available while you are inside. Remote power is not cut immediately after unlocking.",
    "المسافة تقديرية لأن BLE تقيس قوة الإشارة، وتتأثر بالجدران ومكان الهاتف. فعّلها بعد اختبارها حول السيارة.": "Distance is approximate because BLE measures signal strength and is affected by walls and phone placement. Enable after testing around the vehicle.",
    "حفظ وإرسال": "Save and send",
    " م": " m",
    "المظهر": "Appearance",
    "داكن": "Dark",
    "فاتح": "Light",
    "حسب النظام": "System",
    "حجم الخط": "Text size",
    "صغير": "Small",
    "عادي": "Normal",
    "كبير": "Large",
    "أكبر": "Extra large",
    "اللغة": "Language",
    "العربية": "العربية",
    "المظهر واللغة": "Appearance and language",
    "وحدة السرعة": "Speed unit",
    "درجة الحرارة": "Temperature",
    "فولت البطارية يُقرأ تلقائياً من Firmware الـESP؛ ماكو مفتاح محلي وهمي.": "Battery voltage is read automatically by ESP firmware. There is no simulated local switch.",
    "السيارة والقراءات": "Vehicle and readings",
    "تشغيل وإطفاء المحرك": "Engine start and stop",
    "الاقتراب والابتعاد": "Approach and departure",
    "القفل والفتح": "Lock and unlock",
    "حالة OBD": "OBD status",
    "مضافة حماية من إشعار إطفاء كاذب أثناء الحركة ومن تكرار إشعار الاقتراب.": "Includes protection against false engine-off notifications while moving and repeated approach notifications.",
    "الإشعارات": "Notifications",
    "حفظ ترتيب الأولوية": "Save priority order",
    "ارفع أو نزّل أي مسار. الأوامر العادية تتبع هذا التسلسل، بينما الدخول الذكي Keyless يبقى BLE أولاً حتى يظل سريع.": "Move any route up or down. Normal commands follow this order. Smart entry always prefers BLE for fast response.",
    "أولوية الاتصال": "Connection priority",
    "تشغيل Wi-Fi بالـESP": "Enable ESP Wi-Fi",
    "التحكم عن بُعد": "Remote access",
    "ONLINE عبر الإنترنت": "ONLINE over Internet",
    "غير متصل بالسحابة": "Cloud disconnected",
    "جاري البحث...": "Searching…",
    "بحث عن الشبكات": "Search networks",
    "الشبكة": "Network",
    "اختر شبكة": "Select network",
    "اسم الشبكة SSID": "Network name SSID",
    "كلمة مرور الشبكة": "Network password",
    "نسيان الشبكة": "Forget network",
    "البحث يدوي فقط، وماكو Scan مستمر. بهالشكل نقلل تأثير Wi-Fi على BLE أثناء الاستخدام الطبيعي.": "Search is manual only, with no continuous scan. This reduces Wi-Fi interference with BLE during normal use.",
    "إذا الإنترنت شغال، أوامر السيارة تروح MQTT عبر الشريحة أو Wi-Fi؛ BLE يبقى للدخول الذكي، ويرجع fallback محلي فقط إذا انقطع الإنترنت.": "With Internet available, vehicle commands use MQTT over cellular or Wi-Fi. BLE handles smart entry and provides local fallback when Internet is unavailable.",
    "Wi-Fi الـESP": "ESP Wi-Fi",
    "تشغيل الشريحة / 4G": "Enable cellular / 4G",
    "قوة الإشارة": "Signal strength",
    "تسجيل الشبكة": "Network registration",
    "مسجل": "Registered",
    "غير مسجل": "Not registered",
    "بيانات الإنترنت": "Internet data",
    "غير متصلة": "Disconnected",
    "مسار الإنترنت": "Internet route",
    "الشريحة": "Cellular",
    "اسم مستخدم APN - اختياري": "APN username — Optional",
    "كلمة مرور APN - اختيارية": "APN password — Optional",
    "SIM PIN - إذا الشريحة تحتاجه": "SIM PIN — If required",
    "بث نت الشريحة كنقطة اتصال": "Share cellular Internet as a hotspot",
    "اسم نقطة الاتصال": "Hotspot name",
    "كلمة مرور نقطة الاتصال": "Hotspot password",
    "نقطة الاتصال شغالة": "Hotspot active",
    "نقطة الاتصال متوقفة": "Hotspot off",
    "حفظ واتصال": "Save and connect",
    "مسح إعدادات الشريحة": "Clear cellular settings",
    "الـAPN الافتراضي مضبوط على internet. اسم المستخدم وكلمة المرور وSIM PIN اختيارية حسب شركة الشريحة.": "Default APN is internet. Username, password and SIM PIN are optional depending on the carrier.",
    "الشريحة والـ4G": "Cellular and 4G",
    "وضع المطور": "Developer mode",
    "حالة BLE": "BLE status",
    "وضع المطور للـLogs وCAN/OBD والفحص، ولا يغيّر مخارج السيارة وحده.": "Developer mode shows logs and CAN/OBD diagnostics. It does not change vehicle outputs by itself.",
    "التشخيص وCAN": "Diagnostics and CAN",
    "اتصال MQTT المشفّر": "Encrypted MQTT connection",
    "عنوان السيرفر": "Server address",
    "اسم المستخدم": "Username",
    "كلمة المرور": "Password",
    "TLS فقط، وكلمة المرور محفوظة في Keychain داخل الآيفون.": "TLS only. The password is stored in the iPhone Keychain.",
    "النظام والتحديث": "System and updates",
    "الإعدادات": "Settings",
    "ماكو ESP محدد": "No ESP selected",
    "انحفظ الترتيب بالآيفون وانرسل للـESP": "Order saved on iPhone and sent to ESP",
    "تعذر حفظ الأولوية": "Could not save priority",
    "الشريحة / 4G": "Cellular / 4G",
    "تم إرسال أمر البحث للـESP": "Search command sent to ESP",
    "تم إرسال أمر تشغيل Wi-Fi": "Wi-Fi enable command sent",
    "تم إرسال أمر إطفاء Wi-Fi": "Wi-Fi disable command sent",
    "اختار الشبكة أولاً": "Select a network first",
    "جاري اتصال ESP بالشبكة": "ESP is connecting to the network",
    "تم إرسال أمر نسيان الشبكة": "Forget network command sent",
    "جاري البحث": "Searching",
    "تم العثور على شبكات": "Networks found",
    "ما لكه شبكات": "No networks found",
    "فشل البحث": "Search failed",
    "اختار شبكة": "Select a network",
    "تم نسيان الشبكة": "Network forgotten",
    "Wi-Fi مطفأ": "Wi-Fi off",
    "تم إرسال أمر تشغيل الشريحة": "Cellular enable command sent",
    "تم إرسال أمر إطفاء بيانات الشريحة": "Cellular data disable command sent",
    "أدخل APN": "Enter APN",
    "تم حفظ إعدادات الشريحة وجاري الفحص": "Cellular settings saved; checking connection",
    "جاري فحص الشريحة والشبكة": "Checking modem and network",
    "تم إرسال أمر مسح إعدادات الشريحة": "Clear cellular settings command sent",
    "الشريحة جاهزة": "Modem ready",
    "مسجلة على الشبكة": "Registered on network",
    "الإنترنت متصل": "Internet connected",
    "جاري الفحص": "Checking",
    "تحتاج SIM PIN": "SIM PIN required",
    "الشريحة غير موجودة": "SIM missing",
    "فشل تسجيل الشبكة": "Network registration failed",
    "فشل اتصال البيانات": "Data connection failed",
    "الشريحة مطفأة": "Cellular off",
    "بانتظار الفحص": "Waiting for check",
    "رقم المنفذ غير صحيح": "Invalid port number",
    "إصدار التطبيق": "App version",
    "Firmware المطلوب": "Required firmware",
    "التحديث": "Updates",
    "تحديث ESP عبر OTA يبقى من صفحة الفحص/الصيانة.": "ESP OTA updates are available on the diagnostics and maintenance page.",
    "إعدادات الواجهة تُحفظ محلياً وتبقى بعد إعادة تشغيل التطبيق.": "Interface settings are saved locally and remain after restarting the app.",
    "إرسال أمر القفل": "Send lock command",
    "إرسال أمر الفتح": "Send unlock command",
    "إرسال أمر التشغيل": "Send start command",
    "فتح الدخول الذكي": "Smart entry unlock",
    "قفل الدخول الذكي": "Smart entry lock",
    "تحديث وجود الدخول الذكي": "Update smart entry presence",
    "فحص الأبواب": "Test doors",
    "فحص الهورن": "Test horn",
    "فحص الإضاءة": "Test lights",
    "فحص إشارة يسار": "Test left turn signal",
    "فحص إشارة يمين": "Test right turn signal",
    "مزامنة حالة المالك": "Sync owner status",
    "تسجيل جهاز المالك": "Register owner device",
    "طلب ربط جهاز": "Request device pairing",
    "موافقة جهاز مالك": "Approve owner device",
    "رفض جهاز مالك": "Reject owner device",
    "حذف جهاز مالك": "Remove owner device",
    "مسح أجهزة المالك": "Clear owner devices",
    "تحديث إعدادات الدخول الذكي": "Update smart entry settings",
    "تحديث إعدادات ESP": "Update ESP settings",
    "تحديث ESP عبر 4G": "Update ESP via 4G",
    "تغيير وضع الصيانة": "Change maintenance mode",
    "تغيير توفير الطاقة": "Change power saving",
    "إضافة بطاقة NFC": "Add NFC card",
    "حفظ قطعة OBD": "Save OBD adapter",
    "بحث عن قطعة OBD": "Search OBD adapter",
    "نسيان قطعة OBD": "Forget OBD adapter",
    "فحص أخطاء OBD": "Scan OBD trouble codes",
    "مسح أخطاء OBD": "Clear OBD trouble codes",
    "تأكيد استلام حدث ESP": "Confirm ESP event received",
    "تحديث Wi-Fi للـESP": "Update ESP Wi-Fi",
    "بحث شبكات Wi-Fi": "Search Wi-Fi networks",
    "نسيان شبكة Wi-Fi": "Forget Wi-Fi network",
    "تحديث إعدادات الشريحة": "Update cellular settings",
    "فحص اتصال الشريحة": "Check cellular connection",
    "تحديث أولوية الاتصال": "Update connection priority",
    "بطاقة أو ميدالية": "Card or key fob",
    "هاتف أندرويد HCE": "Android HCE phone",
    "فتح + تشغيل عن بُعد": "Unlock + Remote start",
    "معلومة": "Information",
    "يحتاج انتباه": "Needs attention",
    "تحذير": "Warning",
]
private let journeyStoredArabic = Dictionary(journeyStoredTranslations.map { ($0.value, $0.key) }, uniquingKeysWith: { first, _ in first })

private let journeyStoredPatterns: [(NSRegularExpression, String, NSRegularExpression, String)] = {
    let entries: [(String, String, String, String)] = [
        ("^رفض\\ خادم\\ MQTT\\ الاتصال:\\ (.+?)$", "MQTT server refused connection: $1", "^MQTT\\ server\\ refused\\ connection:\\ (.+?)$", "رفض خادم MQTT الاتصال: $1"),
        ("^القراءة\\ الحالية\\ (.+?)°C\\ وتحتاج\\ تحققاً\\ فورياً\\ من\\ القراءة\\ والحالة\\.$", "The current reading is $1°C. Check the reading and vehicle condition immediately.", "^The\\ current\\ reading\\ is\\ (.+?)°C\\.\\ Check\\ the\\ reading\\ and\\ vehicle\\ condition\\ immediately\\.$", "القراءة الحالية $1°C وتحتاج تحققاً فورياً من القراءة والحالة."),
        ("^القراءة\\ الحالية\\ (.+?)°C\\.$", "The current reading is $1°C.", "^The\\ current\\ reading\\ is\\ (.+?)°C\\.$", "القراءة الحالية $1°C."),
        ("^تمت\\ قراءة\\ (.+?)\\ كود:\\ (.+?)\\.$", "Read $1 codes: $2.", "^Read\\ (.+?)\\ codes:\\ (.+?)\\.$", "تمت قراءة $1 كود: $2."),
        ("^ابتعد\\ الهاتف\\ أو\\ انقطع\\ BLE\\.\\ سيقفل\\ ESP\\ السيارة\\ بعد\\ (.+?)\\ ثانية\\ إذا\\ لم\\ يرجع\\ اتصال\\ القرب\\.$", "The phone moved away or BLE disconnected. ESP will lock the vehicle after $1 seconds unless proximity returns.", "^The\\ phone\\ moved\\ away\\ or\\ BLE\\ disconnected\\.\\ ESP\\ will\\ lock\\ the\\ vehicle\\ after\\ (.+?)\\ seconds\\ unless\\ proximity\\ returns\\.$", "ابتعد الهاتف أو انقطع BLE. سيقفل ESP السيارة بعد $1 ثانية إذا لم يرجع اتصال القرب."),
        ("^BLE\\ متصل\\ (.+?)\\ dBm$", "BLE connected $1 dBm", "^BLE\\ connected\\ (.+?)\\ dBm$", "BLE متصل $1 dBm"),
        ("^جاري\\ تأكيد\\ أمر\\ BLE\\ \\((.+?)\\ بايت\\)$", "Confirming BLE command ($1 bytes)", "^Confirming\\ BLE\\ command\\ \\((.+?)\\ bytes\\)$", "جاري تأكيد أمر BLE ($1 بايت)"),
        ("^فشل\\ إرسال\\ أمر\\ BLE:\\ (.+?)$", "BLE command failed: $1", "^BLE\\ command\\ failed:\\ (.+?)$", "فشل إرسال أمر BLE: $1"),
        ("^(.+?)\\ مفعّل$", "$1 enabled", "^(.+?)\\ enabled$", "$1 مفعّل"),
        ("^(.+?)\\ ثوانٍ$", "$1 seconds", "^(.+?)\\ seconds$", "$1 ثوانٍ"),
        ("^تأكيد\\ (.+?)\\ من\\ اختصار\\ الشاشة\\ الرئيسية$", "Confirm $1 from the home screen shortcut", "^Confirm\\ (.+?)\\ from\\ the\\ home\\ screen\\ shortcut$", "تأكيد $1 من اختصار الشاشة الرئيسية"),
        ("^قبل\\ (.+?)\\ د$", "$1 min ago", "^(.+?)\\ min\\ ago$", "قبل $1 د"),
        ("^طلب\\ جديد:\\ (.+?)…$", "New request: $1…", "^New\\ request:\\ (.+?)…$", "طلب جديد: $1…"),
        ("^تنبيه\\ الحرارة:\\ (.+?)°C$", "Temperature alert: $1°C", "^Temperature\\ alert:\\ (.+?)°C$", "تنبيه الحرارة: $1°C"),
        ("^حد\\ RPM:\\ (.+?)$", "RPM threshold: $1", "^RPM\\ threshold:\\ (.+?)$", "حد RPM: $1"),
        ("^سرعة\\ التجربة:\\ (.+?)\\ km/h$", "Test speed: $1 km/h", "^Test\\ speed:\\ (.+?)\\ km/h$", "سرعة التجربة: $1 km/h"),
        ("^حرارة\\ التجربة:\\ (.+?)°C$", "Test temperature: $1°C", "^Test\\ temperature:\\ (.+?)°C$", "حرارة التجربة: $1°C"),
        ("^RPM\\ التجريبي:\\ (.+?)$", "Test RPM: $1", "^Test\\ RPM:\\ (.+?)$", "RPM التجريبي: $1"),
        ("^(.+?)\\ ثانية$", "$1 seconds", "^(.+?)\\ seconds$", "$1 ثانية"),
        ("^(.+?)\\ /\\ 10\\ مسجّل$", "$1 / 10 registered", "^(.+?)\\ /\\ 10\\ registered$", "$1 / 10 مسجّل"),
        ("^فشل\\ التحديث:\\ HTTP\\ (.+?)$", "Update failed: HTTP $1", "^Update\\ failed:\\ HTTP\\ (.+?)$", "فشل التحديث: HTTP $1"),
        ("^فشل\\ الرفع:\\ (.+?)$", "Upload failed: $1", "^Upload\\ failed:\\ (.+?)$", "فشل الرفع: $1"),
        ("^اكتمل:\\ (.+?)\\ مدعوم$", "Complete: $1 supported", "^Complete:\\ (.+?)\\ supported$", "اكتمل: $1 مدعوم"),
        ("^قطع\\ ظهرت\\ للـESP:\\ (.+?)$", "Adapters found by ESP: $1", "^Adapters\\ found\\ by\\ ESP:\\ (.+?)$", "قطع ظهرت للـESP: $1"),
        ("^شبكات\\ ظهرت\\ للـESP:\\ (.+?)$", "Networks found by ESP: $1", "^Networks\\ found\\ by\\ ESP:\\ (.+?)$", "شبكات ظهرت للـESP: $1"),
        ("^بدون\\ اسم\\ \\[(.+?)\\]$", "Unnamed [$1]", "^Unnamed\\ \\[(.+?)\\]$", "بدون اسم [$1]"),
        ("^القفل\\ مضبوط\\ على\\ (.+?)\\ م\\ أو\\ أكثر\\ حتى\\ لا\\ يفتح\\ ويقفل\\ بسرعة\\.$", "Lock distance is set to $1 m or more to prevent rapid locking and unlocking.", "^Lock\\ distance\\ is\\ set\\ to\\ (.+?)\\ m\\ or\\ more\\ to\\ prevent\\ rapid\\ locking\\ and\\ unlocking\\.$", "القفل مضبوط على $1 م أو أكثر حتى لا يفتح ويقفل بسرعة."),
        ("^(.+?)(.+?)$", "$1$2", "^(.+?)(.+?)$", "$1$2"),
        ("^متصل:\\ (.+?)$", "Connected: $1", "^Connected:\\ (.+?)$", "متصل: $1"),
    ]
    return entries.compactMap { entry in
        guard let arabic = try? NSRegularExpression(pattern: entry.0),
              let english = try? NSRegularExpression(pattern: entry.2) else { return nil }
        return (arabic, entry.1, english, entry.3)
    }
}()
